# Generated by Django 4.2.5 on 2023-12-09 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='user_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
