# Generated by Django 4.2.5 on 2023-09-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='photo',
            field=models.URLField(max_length=60),
        ),
    ]
